# To start/stop the services, use docker-compose up/down
version: "3.2"

services:
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    image: imse/0303628_frontend_prod
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    depends_on:
      - backend-prod
    networks:
      imsenet:

  backend-prod:
    build:
      # set context for build command explicitly
      context: ./backend
    image: imse/0303628_backend
    environment:
      MONGO_URI: 'mongodb://admin:imse@mongo:27017/slr?authSource=admin'
      FLASK_DEBUG: 0
    depends_on:
      - mongo
    networks:
      imsenet:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: imse
    networks:
      imsenet:

networks:
  imsenet:
volumes:
  mongo:
