# Use an official Python runtime as a parent image
FROM python:2.7-slim


# Add file to image for later use
ADD requirements.txt /requirements.txt

# Use pip to install dependencies
RUN pip install --trusted-host pypi.python.org -r /requirements.txt

# Set the working directory to /app
WORKDIR /app

# Copy the shared libraries to the container
ADD libraries /app/libraries

# Copy the example source directory contents into the container at /app
ADD example /app/src


# Set environment variable pointing to container-local libraries
ENV PYTHONPATH /app

# Run app.py when the container launches
CMD ["python", "src/app.py"]
